export interface ProductData {
  slug: string;
  name: string;
  price: string;
  priceValue: number;
  inStock: boolean;
  sizingOptions: string[];
  colours: string[];
  sizes: string[];
  details: string;
  materials: string[];
  madeToOrder: string;
  fit: string;
  image: string;
  images: string[];
}

export const allProducts: ProductData[] = [
  {
    slug: "cena-flat",
    name: "cena flat",
    price: "N185 000.00",
    priceValue: 185000,
    inStock: true,
    sizingOptions: ["Standard", "Wide"],
    colours: ["black", "brown", "beige"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo cena flat shoes featuring a curved defined silhouette",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size. If you're in-between sizes, size up.",
    image: "/images/product-1.jpg",
    images: ["/images/product-1.jpg", "/images/product-2.jpg", "/images/product-3.jpg", "/images/product-4.jpg"],
  },
  {
    slug: "vie",
    name: "vie",
    price: "N190 000.00",
    priceValue: 190000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["black", "brown"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo vie shoes featuring a minimalist design",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-2.jpg",
    images: ["/images/product-2.jpg", "/images/product-1.jpg", "/images/product-3.jpg", "/images/product-4.jpg"],
  },
  {
    slug: "cena-platform",
    name: "cena platform",
    price: "N220 000.00",
    priceValue: 220000,
    inStock: true,
    sizingOptions: ["Standard", "Wide"],
    colours: ["black", "brown", "beige"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo cena platform shoes featuring a curved defined silhouette",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped platform and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size. If you're in-between sizes, size up.",
    image: "/images/product-3.jpg",
    images: ["/images/product-3.jpg", "/images/product-3-alt-1.jpg", "/images/product-3-alt-2.jpg", "/images/product-3-alt-3.jpg"],
  },
  {
    slug: "mia",
    name: "mia",
    price: "N205 000.00",
    priceValue: 205000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["black", "brown", "beige"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo mia sandals featuring a bold silhouette",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped platform and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size. If you're in-between sizes, size up.",
    image: "/images/product-4.jpg",
    images: ["/images/product-4.jpg", "/images/product-1.jpg", "/images/product-2.jpg", "/images/product-3.jpg"],
  },
  {
    slug: "jan",
    name: "jan",
    price: "N350 000.00",
    priceValue: 350000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["black", "brown"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo jan shoes featuring intricate woven leather details",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-5.jpg",
    images: ["/images/product-5.jpg", "/images/product-6.jpg", "/images/product-7.jpg", "/images/product-8.jpg"],
  },
  {
    slug: "nino",
    name: "nino",
    price: "N350 000.00",
    priceValue: 350000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["black", "brown"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo nino shoes featuring woven leather construction",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-6.jpg",
    images: ["/images/product-6.jpg", "/images/product-5.jpg", "/images/product-7.jpg", "/images/product-8.jpg"],
  },
  {
    slug: "dee",
    name: "dee",
    price: "N190 000.00",
    priceValue: 190000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["black", "white"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo dee platform sandals",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped platform and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size. If you're in-between sizes, size up.",
    image: "/images/product-7.jpg",
    images: ["/images/product-7.jpg", "/images/product-8.jpg", "/images/product-5.jpg", "/images/product-6.jpg"],
  },
  {
    slug: "mai",
    name: "mai",
    price: "N155 000.00",
    priceValue: 155000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["black", "white"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo mai minimalist sandals",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-8.jpg",
    images: ["/images/product-8.jpg", "/images/product-7.jpg", "/images/product-5.jpg", "/images/product-6.jpg"],
  },
  {
    slug: "blu",
    name: "blu",
    price: "N320 000.00",
    priceValue: 320000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["black", "brown"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo blu woven leather sandals",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-9.jpg",
    images: ["/images/product-9.jpg", "/images/product-10.jpg", "/images/product-11.jpg", "/images/product-12.jpg"],
  },
  {
    slug: "nue",
    name: "nue",
    price: "N300 000.00",
    priceValue: 300000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["black", "brown"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo nue woven leather sandals",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-10.jpg",
    images: ["/images/product-10.jpg", "/images/product-9.jpg", "/images/product-11.jpg", "/images/product-12.jpg"],
  },
  {
    slug: "bob",
    name: "bob",
    price: "N190 000.00",
    priceValue: 190000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["black", "white"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo bob platform sandals",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped platform and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size. If you're in-between sizes, size up.",
    image: "/images/product-11.jpg",
    images: ["/images/product-11.jpg", "/images/product-12.jpg", "/images/product-9.jpg", "/images/product-10.jpg"],
  },
  {
    slug: "leo",
    name: "leo",
    price: "N190 000.00",
    priceValue: 190000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["black", "white"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo leo minimalist sandals",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-12.jpg",
    images: ["/images/product-12.jpg", "/images/product-11.jpg", "/images/product-9.jpg", "/images/product-10.jpg"],
  },
  {
    slug: "tre",
    name: "tre",
    price: "N150 000.00",
    priceValue: 150000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["purple", "black"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo tre slide sandals",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-13.jpg",
    images: ["/images/product-13.jpg", "/images/product-14.jpg", "/images/product-15.jpg", "/images/product-16.jpg"],
  },
  {
    slug: "jin",
    name: "jin",
    price: "N150 000.00",
    priceValue: 150000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["purple", "black"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo jin slide sandals",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-14.jpg",
    images: ["/images/product-14.jpg", "/images/product-13.jpg", "/images/product-15.jpg", "/images/product-16.jpg"],
  },
  {
    slug: "rin",
    name: "rin",
    price: "N180 000.00",
    priceValue: 180000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["white", "black"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo rin strappy sandals",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-15.jpg",
    images: ["/images/product-15.jpg", "/images/product-16.jpg", "/images/product-13.jpg", "/images/product-14.jpg"],
  },
  {
    slug: "lee",
    name: "lee",
    price: "N160 000.00",
    priceValue: 160000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["white", "black"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo lee strappy sandals",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-16.jpg",
    images: ["/images/product-16.jpg", "/images/product-15.jpg", "/images/product-13.jpg", "/images/product-14.jpg"],
  },
  {
    slug: "susu",
    name: "susu",
    price: "N180 000.00",
    priceValue: 180000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["white", "black"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo susu platform shoes",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped platform and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size. If you're in-between sizes, size up.",
    image: "/images/product-17.jpg",
    images: ["/images/product-17.jpg", "/images/product-18.jpg", "/images/product-19.jpg", "/images/product-20.jpg"],
  },
  {
    slug: "nita",
    name: "nita",
    price: "N185 000.00",
    priceValue: 185000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["black", "brown"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo nita platform shoes",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped platform and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size. If you're in-between sizes, size up.",
    image: "/images/product-18.jpg",
    images: ["/images/product-18.jpg", "/images/product-17.jpg", "/images/product-19.jpg", "/images/product-20.jpg"],
  },
  {
    slug: "rio",
    name: "rio",
    price: "N350 000.00",
    priceValue: 350000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["orange", "brown"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo rio woven leather sandals",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-19.jpg",
    images: ["/images/product-19.jpg", "/images/product-20.jpg", "/images/product-17.jpg", "/images/product-18.jpg"],
  },
  {
    slug: "sia",
    name: "sia",
    price: "N340 000.00",
    priceValue: 340000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["orange", "brown"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo sia woven leather sandals",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-20.jpg",
    images: ["/images/product-20.jpg", "/images/product-19.jpg", "/images/product-17.jpg", "/images/product-18.jpg"],
  },
  {
    slug: "jane",
    name: "jane",
    price: "N165 000.00",
    priceValue: 165000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["black", "brown"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo jane loafers",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-21.jpg",
    images: ["/images/product-21.jpg", "/images/product-22.jpg", "/images/product-23.jpg", "/images/product-24.jpg"],
  },
  {
    slug: "vela",
    name: "vela",
    price: "N185 000.00",
    priceValue: 185000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["beige", "black"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo vela flat shoes",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-22.jpg",
    images: ["/images/product-22.jpg", "/images/product-21.jpg", "/images/product-23.jpg", "/images/product-24.jpg"],
  },
  {
    slug: "riro",
    name: "riro",
    price: "N185 000.00",
    priceValue: 185000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["white", "black"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo riro sandals",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-23.jpg",
    images: ["/images/product-23.jpg", "/images/product-24.jpg", "/images/product-21.jpg", "/images/product-22.jpg"],
  },
  {
    slug: "vera",
    name: "vera",
    price: "N175 000.00",
    priceValue: 175000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["brown", "black"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo vera heeled sandals",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size. If you're in-between sizes, size up.",
    image: "/images/product-24.jpg",
    images: ["/images/product-24.jpg", "/images/product-23.jpg", "/images/product-21.jpg", "/images/product-22.jpg"],
  },
  {
    slug: "halo",
    name: "halo",
    price: "N150 000.00",
    priceValue: 150000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["black", "brown"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo halo flat shoes",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-25.jpg",
    images: ["/images/product-25.jpg", "/images/product-26.jpg", "/images/product-27.jpg", "/images/product-28.jpg"],
  },
  {
    slug: "april",
    name: "april",
    price: "N190 000.00",
    priceValue: 190000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["beige", "black"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo april flat shoes",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-26.jpg",
    images: ["/images/product-26.jpg", "/images/product-25.jpg", "/images/product-27.jpg", "/images/product-28.jpg"],
  },
  {
    slug: "lino",
    name: "lino",
    price: "N190 000.00",
    priceValue: 190000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["black", "brown"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo lino flat shoes",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-27.jpg",
    images: ["/images/product-27.jpg", "/images/product-28.jpg", "/images/product-25.jpg", "/images/product-26.jpg"],
  },
  {
    slug: "nulu",
    name: "nulu",
    price: "N195 000.00",
    priceValue: 195000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["black", "brown"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo nulu flat shoes",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-28.jpg",
    images: ["/images/product-28.jpg", "/images/product-27.jpg", "/images/product-25.jpg", "/images/product-26.jpg"],
  },
  {
    slug: "sari",
    name: "sari",
    price: "N205 000.00",
    priceValue: 205000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["beige", "black"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo sari flat shoes",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-29.jpg",
    images: ["/images/product-29.jpg", "/images/product-30.jpg", "/images/product-1.jpg", "/images/product-2.jpg"],
  },
  {
    slug: "balu",
    name: "balu",
    price: "N195 000.00",
    priceValue: 195000,
    inStock: true,
    sizingOptions: ["Standard"],
    colours: ["beige", "black"],
    sizes: ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
    details: "selo balu flat shoes",
    materials: ["Upper & Lining – Leather", "Sole – Leather wrapped and eva sole"],
    madeToOrder: "Every pair is designed and handmade in Lagos, Nigeria. Please allow up to 2 weeks for production.",
    fit: "This style runs true to size. Select your standard size.",
    image: "/images/product-30.jpg",
    images: ["/images/product-30.jpg", "/images/product-29.jpg", "/images/product-1.jpg", "/images/product-2.jpg"],
  },
];

export function getProductBySlug(slug: string): ProductData | undefined {
  return allProducts.find((p) => p.slug === slug);
}
